const zh = {
  title: '来源分析',
  options: '分析选项',
  done: '完成',
  description: '从来源类别、网站、外链、搜索引擎和关键词了解流量质量。',
  channels: '来路概览',
  domains: '来路汇总',
  urls: '外部链接',
  engines: '搜索引擎',
  keywords: '关键词',
  name: '来源',
  engine: '搜索引擎',
  keyword: '关键词',
  pageviews: '浏览量（PV）',
  visitors: '访客数（UV）',
  visits: '访问次数',
  newVisitors: '新访客',
  ips: '已记录 IP 数',
  ipCoverage: 'IP 覆盖率',
  bounceRate: '跳出率',
  pagesPerVisit: '平均访问页数',
  averageDuration: '平均访问时长',
  total: '当前视图合计',
  search: '搜索来源、引擎或关键词',
  all: '全部',
  available: '已提供关键词',
  unavailable: '未提供 / 无法解码',
  keywordState: '关键词状态',
  matrix: '按引擎交叉查看（PV / UV）',
  columns: '显示指标',
  export: '导出当前页 CSV',
  perPage: '每页行数',
  sort: '排序指标',
  order: '排序方式',
  asc: '升序',
  desc: '降序',
  exclude: '排除噪声',
  excludeDomain: '排除此网站',
  excludeKeyword: '排除此关键词',
  clearExclusions: '清除排除项',
  excludedDomains: '已排除网站',
  excludedKeywords: '已排除关键词',
  exclusionsNote: '排除项仅过滤此浏览器中的报表，不删除记录或停止采集；可随时恢复。',
  unavailableNote:
    '仅从来源地址中已保存的搜索参数提取 UTF-8 明文关键词。搜索引擎隐藏、空值、占位值或无法解码的旧编码统一显示为“未提供 / 无法解码”，不会用推广词替代。',
  metricsNote:
    '来源取每次访问最早的已记录页面，包含所选期间之前的入口。筛选先匹配访问，再统计这些访问在所选期间内的页面浏览与时长；跳出基于该访问的全部已记录页面和事件。各行 UV、新访客和 IP 数不可直接相加。',
  identityNote:
    '新访客基于现存首次页面浏览记录。访客身份默认按月轮换，删除历史记录也会影响新老识别。',
  ipNote:
    'IP 数仅去重已保存的地址；覆盖率是具有 IP 记录的访问比例。历史未采集的 IP 无法补回，未知不会算作 0 个 IP 或用 UV 替代。',
  urlNote:
    '外部链接不含已识别的搜索引擎及自然搜索流量。来源协议没有保存；此处按已记录的主机、路径和查询参数还原来源地址。',
  empty: '当前条件下暂无来源数据。',
  noIp: '未记录',
  seconds: '秒',
  minutes: '分',
};
const en: typeof zh = {
  title: 'Sources analysis',
  options: 'Analysis options',
  done: 'Done',
  description:
    'Compare traffic quality across channels, websites, referrers, search engines and keywords.',
  channels: 'Source overview',
  domains: 'Source websites',
  urls: 'External links',
  engines: 'Search engines',
  keywords: 'Keywords',
  name: 'Source',
  engine: 'Search engine',
  keyword: 'Keyword',
  pageviews: 'Pageviews (PV)',
  visitors: 'Visitors (UV)',
  visits: 'Visits',
  newVisitors: 'New visitors',
  ips: 'Recorded IPs',
  ipCoverage: 'IP coverage',
  bounceRate: 'Bounce rate',
  pagesPerVisit: 'Pages per visit',
  averageDuration: 'Avg. visit duration',
  total: 'Current view total',
  search: 'Search source, engine or keyword',
  all: 'All',
  available: 'Provided keywords',
  unavailable: 'Not provided / undecodable',
  keywordState: 'Keyword availability',
  matrix: 'Engine matrix (PV / UV)',
  columns: 'Visible metrics',
  export: 'Export current page CSV',
  perPage: 'Rows per page',
  sort: 'Sort metric',
  order: 'Sort direction',
  asc: 'Ascending',
  desc: 'Descending',
  exclude: 'Exclude noise',
  excludeDomain: 'Exclude this website',
  excludeKeyword: 'Exclude this keyword',
  clearExclusions: 'Clear exclusions',
  excludedDomains: 'Excluded websites',
  excludedKeywords: 'Excluded keywords',
  exclusionsNote:
    'Exclusions filter reports in this browser. They do not delete records or stop collection and can be cleared anytime.',
  unavailableNote:
    'Keywords use only retained UTF-8 search parameters from referrer URLs. Withheld, empty, placeholder or undecodable values remain unavailable; campaign terms are never substituted.',
  metricsNote:
    'Each visit is attributed to its earliest retained pageview, including entries before this period. Filters select visits; metrics use their in-period pageviews and duration, while bounce status uses the whole recorded visit. Row-level UV, new visitors and IPs are not additive.',
  identityNote:
    'New visitors use their first retained pageview. Identity rotation (monthly by default) and deleted history affect recognition.',
  ipNote:
    'Only stored IP addresses are counted. Coverage is the share of visits with an IP record. Missing historical addresses cannot be recovered or replaced with visitor counts.',
  urlNote:
    'External links exclude recognized search engines and organic search. Referrer protocols were not stored; addresses combine the retained host, path and query string.',
  empty: 'No sources match the current selection.',
  noIp: 'Not recorded',
  seconds: 's',
  minutes: 'm',
};
const categoryNames = {
  zh: {
    direct: '直接访问',
    search: '搜索引擎',
    external: '外部链接',
    social: '社交媒体',
    email: '邮件',
    paid: '付费推广',
    ai: 'AI 助手',
    campaign: '其他推广',
  },
  en: {
    direct: 'Direct',
    search: 'Search',
    external: 'External referral',
    social: 'Social',
    email: 'Email',
    paid: 'Paid',
    ai: 'AI assistants',
    campaign: 'Other campaigns',
  },
};
export const getSourceCopy = (locale: string) => (locale.startsWith('zh') ? zh : en);
export const getSourceCategoryNames = (locale: string) =>
  locale.startsWith('zh') ? categoryNames.zh : categoryNames.en;
export type SourceCopy = typeof zh;
