export const contentCopy = {
  en: {
    title: 'Content analysis',
    options: 'Report options',
    mode: 'Content view',
    fullUrl: 'Full page address',
    path: 'Path',
    titleMode: 'Page title',
    entry: 'Landing pages',
    exit: 'Exit pages',
    hostname: 'Hostnames',
    group: 'Page groups',
    pageviews: 'Pageviews (PV)',
    visitors: 'Visitors (UV)',
    visits: 'Visits',
    newVisitors: 'New visitors',
    entrances: 'Entrances',
    exits: 'Exits',
    exitRate: 'Exit rate',
    bounceRate: 'Landing bounce rate',
    averageDwell: 'Measured dwell time',
    dwellSamples: 'Measured views',
    dwellCoverage: 'Dwell coverage',
    name: 'Page / group',
    summary: 'Matching content',
    search: 'Search pages or groups',
    rows: 'Rows per page',
    orderBy: 'Sort by',
    order: 'Order',
    ascending: 'Ascending',
    descending: 'Descending',
    download: 'Export this page (CSV)',
    unknown: '—',
    methodology: 'How these numbers are calculated',
    definitions:
      'Page addresses combine the recorded hostname, path, query and fragment. Visitors and visits are deduplicated separately. A visit is identified by both visitor ID and visit ID. Landing/exit views list pages observed at the start/end of a visit; their PV includes other matching views of the same page.',
    dwellDefinition:
      'Dwell is the observed interval until the next page in the same visit, including a next page outside the selected dates. The last page has unknown dwell, not zero. The average uses only measured intervals; coverage shows how many views have a next-page timestamp. This is not active attention time.',
    identityDefinition:
      'New visitors are first seen in retained pageview history. Rotating anonymous IDs and deleted history limit recognition. Bounce rate is single-page landing visits without custom events divided by entrances. Exit rate is observed last pages divided by PV; an ongoing visit may still gain another page.',
    groupsDefinition:
      'Rules within a group use OR. A page may belong to multiple groups. Group rows overlap and must not be added together; summary visitors, visits and pageviews are deduplicated across all matching groups.',
    sources: 'Landing source contribution',
    source: 'Referrer',
    direct: 'Direct / unknown',
    contribution: 'Contribution',
    sourceDetail: 'View landing sources',
    allSources: 'All matching landing pages',
    sourceDefinition:
      'Sources use the first page in each visit. At most 50 sources are shown; percentages use all matching entrances.',
    noData: 'No matching pageviews for this period.',
    done: 'Done',
    groupsManage: 'Manage page groups',
    groupName: 'Group name',
    ruleField: 'Match field',
    ruleOperator: 'Match rule',
    ruleValue: 'Value',
    route: 'Path with query and fragment',
    exact: 'Equals',
    prefix: 'Starts with',
    contains: 'Contains',
    addRule: 'Add rule',
    removeRule: 'Remove rule',
    saveGroup: 'Save group',
    newGroup: 'New group',
    edit: 'Edit',
    remove: 'Delete',
    groupHint:
      'For PHP routes, match the route with its query, such as /?products/. Match path prefixes such as /articles/ for directories. Values are literal; % and _ are not wildcards.',
    groupError: 'Enter a group name and at least one nonempty rule.',
    groupLimit: 'Up to 100 groups per website and 20 rules per group.',
    noGroups: 'Create page groups to compare directories or related pages.',
  },
  zh: {
    title: '内容分析',
    options: '分析选项',
    mode: '内容维度',
    fullUrl: '完整页面地址',
    path: '页面路径',
    titleMode: '页面标题',
    entry: '入口页面',
    exit: '退出页面',
    hostname: '受访域名',
    group: '页面分组',
    pageviews: '浏览量 (PV)',
    visitors: '访客数 (UV)',
    visits: '访问次数',
    newVisitors: '新访客数',
    entrances: '入口次数',
    exits: '退出次数',
    exitRate: '退出率',
    bounceRate: '入口跳出率',
    averageDwell: '可测停留时长',
    dwellSamples: '可测浏览次数',
    dwellCoverage: '停留可测比例',
    name: '页面 / 分组',
    summary: '匹配内容合计',
    search: '搜索页面或分组',
    rows: '每页条数',
    orderBy: '排序指标',
    order: '排序方向',
    ascending: '从小到大',
    descending: '从大到小',
    download: '导出本页 CSV',
    unknown: '—',
    methodology: '统计口径',
    definitions:
      '完整地址由已采集的域名、路径、查询参数和页面片段组成。访客与访问次数分别去重，每次访问由访客标识和访问标识共同确定。入口/退出视图列出曾作为访问首末页的页面，其浏览量也包含该页面在其他位置出现的匹配记录。',
    dwellDefinition:
      '停留时长使用同次访问中当前页至下一页的时间间隔，下一页可位于所选日期之外。末页停留未知，不记为零；平均值只计算有下一页时间戳的记录，“停留可测比例”显示这类记录的占比。此指标不等于页面活跃阅读时长。',
    identityDefinition:
      '新访客以保留的浏览历史中首次出现时间判断，匿名标识轮换和历史删除会影响识别。入口跳出率为只有一次浏览且没有自定义事件的入口访问占比。退出率为访问末页次数除以浏览量；进行中的访问仍可能增加后续页面。',
    groupsDefinition:
      '组内规则任意一条匹配即可归组；同一页面可以归入多个分组。分组行可能重叠，不可直接相加；合计浏览量、访客及访问次数会跨分组重新去重。',
    sources: '入口来源贡献',
    source: '引荐来源',
    direct: '直接访问 / 未知',
    contribution: '贡献占比',
    sourceDetail: '查看入口来源',
    allSources: '全部匹配入口页面',
    sourceDefinition:
      '来源取每次访问的第一条浏览记录。最多展示 50 个来源，占比以全部匹配入口次数为分母。',
    noData: '所选时段暂无匹配的浏览记录。',
    done: '完成',
    groupsManage: '管理页面分组',
    groupName: '分组名称',
    ruleField: '匹配字段',
    ruleOperator: '匹配方式',
    ruleValue: '匹配内容',
    route: '路径（含查询参数及片段）',
    exact: '完全等于',
    prefix: '开头匹配',
    contains: '包含',
    addRule: '添加规则',
    removeRule: '移除规则',
    saveGroup: '保存分组',
    newGroup: '新建分组',
    edit: '编辑',
    remove: '删除',
    groupHint:
      'PHP 路由可按 /?products/ 等含查询参数的完整路径匹配；目录可按 /articles/ 等路径前缀匹配。匹配内容按字面理解，% 和 _ 不作为通配符。',
    groupError: '请填写分组名称，并至少设置一条非空规则。',
    groupLimit: '每个网站最多 100 个分组，每个分组最多 20 条规则。',
    noGroups: '建立页面分组后，可比较不同目录或相关页面的表现。',
  },
};
export const getContentCopy = (locale: string) =>
  contentCopy[locale.startsWith('zh') ? 'zh' : 'en'];
