const en = {
  title: 'IP analysis',
  description: 'Review visiting IP addresses and exclude internal or unwanted traffic.',
  addresses: 'IP addresses',
  visitors: 'Visitors',
  visits: 'Visits',
  pageviews: 'Pageviews',
  coverage: 'Visits with an IP',
  missing: 'Visits without an IP',
  lastSeen: 'Last activity',
  addedAt: 'Added on',
  report: 'IP report',
  rules: 'IP exclusions',
  options: 'Report options',
  search: 'Search IP',
  sort: 'Sort by',
  direction: 'Order',
  descending: 'Highest first',
  ascending: 'Lowest first',
  apply: 'Apply',
  export: 'Download CSV',
  exportLimit: 'Download first 10,000 rows',
  empty: 'No IP addresses match these filters.',
  add: 'Add exclusion',
  edit: 'Edit',
  remove: 'Delete',
  enabled: 'Enabled',
  disabled: 'Disabled',
  enable: 'Enable',
  disable: 'Disable',
  exclude: 'Exclude IP',
  pattern: 'IP address or range',
  name: 'Note',
  save: 'Save',
  cancel: 'Cancel',
  invalid: 'Enter a valid IP address, CIDR block, or range of addresses of the same type.',
  duplicate: 'This address or range already exists.',
  limit: 'A website supports up to 200 IP exclusions.',
  failed: 'Unable to save the change. Please try again.',
  exportFailed: 'Export failed. Please try again.',
  note: 'Exclusions apply to future pageviews, events, heatmaps, and recordings. Existing data is kept. Disabling a rule resumes collection.',
  privacy:
    'An IP may represent several visitors. Missing historical IPs cannot be recovered. IP storage can be disabled by the administrator.',
  countNote:
    'Filters select visits; counts include all their pageviews in the selected period. IP search applies to the table; summary cards retain the totals for the selected dates and filters.',
  example: 'Examples: 192.0.2.8, 192.0.2.0/24, 2001:db8::/32, 192.0.2.1-192.0.2.20',
  noRules: 'No IP exclusions configured.',
  readOnly: 'Only website managers can change exclusions.',
};
const zh: typeof en = {
  title: 'IP 分析',
  description: '查看访客 IP 分布，排除内部访问或不需要统计的流量。',
  addresses: '独立 IP 数',
  visitors: '访客数',
  visits: '访问次数',
  pageviews: '浏览量（PV）',
  coverage: '已记录 IP 的访问',
  missing: '缺失 IP 的访问',
  lastSeen: '最近活动时间',
  addedAt: '添加时间',
  report: 'IP 统计',
  rules: 'IP 排除规则',
  options: '报表选项',
  search: '搜索 IP',
  sort: '排序指标',
  direction: '排序方式',
  descending: '从高到低',
  ascending: '从低到高',
  apply: '应用',
  export: '下载 CSV',
  exportLimit: '下载前 10,000 条',
  empty: '当前条件下暂无 IP 记录。',
  add: '添加排除规则',
  edit: '编辑',
  remove: '删除',
  enabled: '已启用',
  disabled: '已停用',
  enable: '启用',
  disable: '停用',
  exclude: '排除此 IP',
  pattern: 'IP 地址或范围',
  name: '备注',
  save: '保存',
  cancel: '取消',
  invalid: '请输入有效的 IP 地址、CIDR 网段，或同类型 IP 的起止范围。',
  duplicate: '该 IP 地址或范围已存在。',
  limit: '每个站点最多可添加 200 条 IP 排除规则。',
  failed: '修改未保存，请稍后重试。',
  exportFailed: '导出失败，请稍后重试。',
  note: '规则生效后，该范围的新浏览、事件、热力图和录制将不再采集；历史数据会保留。停用规则即可恢复采集。',
  privacy: '同一 IP 可能对应多个访客。历史缺失的 IP 无法补回；管理员也可以关闭 IP 存储。',
  countNote:
    '筛选条件用于选出访问，指标包含这些访问在所选时段内的全部浏览。IP 搜索仅影响下方明细，顶部卡片保留所选时段与筛选条件下的汇总。',
  example: '示例：192.0.2.8、192.0.2.0/24、2001:db8::/32、192.0.2.1-192.0.2.20',
  noRules: '尚未设置 IP 排除规则。',
  readOnly: '只有站点管理者可以修改排除规则。',
};
export const getIpCopy = (locale: string) => (locale.startsWith('zh') ? zh : en);
